# Generated by Django 5.1.6 on 2025-03-06 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='left_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='left_parent_child', to='family.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='right_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='right_parent_child', to='family.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='spouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='family.user'),
        ),
    ]
