# Generated by Django 5.1.6 on 2025-03-06 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_user_left_parent_user_right_parent_user_spouse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
    ]
